version: 2.1

orbs:
  android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - run:
          name : Download Dependencies
          #command: ./gradlew build
          command: sudo chmod +x ./gradlew
      - run:
          name: Install Fastlane
          command: bundle install
      - run:
          name: Execute Fastlane
          command: bundle exec fastlane playstore
